Algoritmo "notasamor"

Var
 nota1, nota2, media, media1 : real


Inicio
    Escreva("Digite sua primeira nota amorzinho: ")
    leia(nota1)
    Escreva("Digite a segunda nota princesa: ")
    leia(nota2)
    
    media <- nota1 + nota2
    media1 <- media / 2
    
    escreval("Sua nota final é: Amor da minha vida")
    escreval("brincadeira sua média é : ",media1:4:1)
    escreva("TE AMOOOOOOOOO")
    


Fimalgoritmo